theme: jekyll-theme-minimal
title: Notes & Historical Law Book Links by Rob Logue
show_downloads: false
remote_theme: pages-themes/minimal@0.2.0
plugins:
  - jekyll-remote-theme
assets:
  stylesheet: /custom.css
