theme: jekyll-theme-merlot
title: My Law Notes and Links
description: Historical Law Books, Notes by Rob Logue
logo: https://iowacattails.github.io/My-notes/law-scales.png
show_downloads: false
google_analytics: 
